spring:
  datasource:
    url: jdbc:postgresql://192.168.1.80:5432/test
    username: virst
    password: 111399
  security:
    user:
      name: user
      password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
logging:
  pattern:
    console: "%d{dd-MMM-yyyy HH:mm:ss} %-5level %logger : %msg%n"
